#!/usr/bin/python

##  Copyright (c) 2007-2008 Facebook
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##
## See accompanying file LICENSE or visit the Scribe site at:
## http://developers.facebook.com/scribe/


'''scribe_apache: A modified scribe_cat to support piping from apache to scribe.'''

import datetime
import sys
import os
from scribe import scribe
from thrift.transport import TTransport, TSocket
from thrift.protocol import TBinaryProtocol

if len(sys.argv) == 2:
    category = sys.argv[1]
    host = '127.0.0.1'
    port = 1463
elif len(sys.argv) == 4 and sys.argv[1] == '-h':
    category = sys.argv[3]
    host_port = sys.argv[2].split(':')
    host = host_port[0]
    if len(host_port) > 1:
        port = int(host_port[1])
    else:
        port = 1463
else:
    sys.exit('usage (message is stdin): scribe_cat [-h host[:port]] category')

socket = TSocket.TSocket(host=host, port=port)
transport = TTransport.TFramedTransport(socket)
protocol = TBinaryProtocol.TBinaryProtocol(trans=transport, strictRead=False, strictWrite=False)
client = scribe.Client(iprot=protocol, oprot=protocol)

transport.open()

result = scribe.ResultCode.OK

while 1:
    message = sys.stdin.readline()
    if not message:
        break
    now = datetime.datetime.now()
    timestamp = "%s,%0.3d" % (now.strftime("%Y-%m-%d %H:%M:%S"), now.microsecond / 1000)
    message = "%s %s %s %s" % (timestamp, os.uname()[1], category, message)
    log_entry = scribe.LogEntry(category=category, message=message)
    result = client.Log(messages=[log_entry])

if result == scribe.ResultCode.OK:
    sys.exit()
elif result == scribe.ResultCode.TRY_LATER:
    print >> sys.stderr, "TRY_LATER"
    sys.exit(84)  # 'T'
else:
    sys.exit("Unknown error code.")
